# Generated by Django 5.0.3 on 2025-06-09 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='membresias',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_membresia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BiseccionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecuacion', models.CharField(max_length=255)),
                ('valor_min', models.FloatField()),
                ('valor_max', models.FloatField()),
                ('error_porcentual', models.FloatField()),
                ('raiz_aproximada', models.FloatField()),
                ('iter_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DifferenceDividedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=255)),
                ('x_value', models.FloatField()),
                ('h_value', models.FloatField()),
                ('derivada_fwd', models.FloatField()),
                ('formula_fwd', models.TextField()),
                ('pasos_fwd', models.TextField()),
                ('derivada_bwd', models.FloatField()),
                ('formula_bwd', models.TextField()),
                ('pasos_bwd', models.TextField()),
                ('derivada_cen', models.FloatField()),
                ('formula_cen', models.TextField()),
                ('pasos_cen', models.TextField()),
                ('derivada_exacta', models.FloatField()),
                ('error_fwd', models.FloatField()),
                ('error_bwd', models.FloatField()),
                ('error_cen', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories_burned', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_User', models.CharField(max_length=200)),
                ('apellido_User', models.CharField(max_length=200)),
                ('correo_User', models.CharField(max_length=200)),
                ('password_User', models.CharField(max_length=200)),
                ('membresia_id_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.membresias')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_Historial', models.AutoField(primary_key=True, serialize=False)),
                ('Procesos_Historial', models.TextField()),
                ('id_user_Historial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.usuarios')),
            ],
        ),
    ]
